name: bridgefy
description: The Bridgefy SDK is a state-of-the-art, plug-and-play package that lets people use apps when they don’t have access to the Internet by using mesh networ
version: 1.0.6
homepage: https://bridgefy.me/sdk
repository: https://github.com/bridgefy/bridgefy_flutter
issue_tracker: https://github.com/bridgefy/bridgefy_flutter/issues
topics:
  - network
  - offline
  - mesh
  - ble
  - bluetooth

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.bridgefy.plugin.flutter
        pluginClass: BridgefyPlugin
      ios:
        pluginClass: BridgefyPlugin
