name: bridgefy
description: Bridgefy Flutter SDK
version: 1.0.1
homepage: https://bridgefy.me
repository: https://github.com/bridgefy/bridgefy_flutter
issue_tracker: https://github.com/bridgefy/bridgefy_flutter/issues
topics:
  - network
  - offline
  - mesh
  - messenger
  - chat
  - android
  - ios
  - kotlin
  - swift

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.bridgefy.plugin.flutter
        pluginClass: BridgefyPlugin
      ios:
        pluginClass: BridgefyPlugin
